package com.caresync.service;

import com.caresync.entity.MedicalRecord;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

@Service
public class PrescriptionPdfService {

    private static final float MARGIN = 56f;
    private static final float PAGE_HEIGHT = PDRectangle.LETTER.getHeight();
    private static final float PAGE_WIDTH = PDRectangle.LETTER.getWidth();
    private static final float CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;
    private static final DateTimeFormatter DATE_FMT = DateTimeFormatter.ofPattern("MMMM d, yyyy 'at' h:mm a");

    private static final PDFont REGULAR = PDType1Font.HELVETICA;
    private static final PDFont BOLD = PDType1Font.HELVETICA_BOLD;
    private static final PDFont ITALIC = PDType1Font.HELVETICA_OBLIQUE;

    public byte[] generate(MedicalRecord record) {
        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage(PDRectangle.LETTER);
            document.addPage(page);

            try (PDPageContentStream cs = new PDPageContentStream(document, page)) {
                float y = PAGE_HEIGHT - MARGIN;

                y = line(cs, BOLD, 20, MARGIN, y, "CareSync");
                y = line(cs, REGULAR, 9, MARGIN, y - 16, "Telehealth & Appointment Booking");
                y -= 14;
                y = rule(cs, y);

                y = line(cs, BOLD, 15, MARGIN, y - 28, "Prescription & Visit Summary");
                y = line(cs, REGULAR, 9, MARGIN, y - 16,
                        "Record #" + record.getRecordId() + "  \u00b7  Issued " + record.getCreatedAt().format(DATE_FMT));

                y -= 30;
                float col2X = MARGIN + CONTENT_WIDTH / 2f;
                float rowTop = y;

                y = labelValue(cs, MARGIN, rowTop, "Patient", record.getPatient().getFullName());
                labelValue(cs, col2X, rowTop, "Doctor", record.getDoctor().getFullName());

                rowTop = y - 24;
                y = labelValue(cs, MARGIN, rowTop, "Visit date",
                        record.getAppointment().getAppointmentDate() + "  \u00b7  " + record.getAppointment().getTimeSlot());
                labelValue(cs, col2X, rowTop, "Specialization", nullToDash(record.getDoctor().getSpecialization()));

                y -= 10;
                y = rule(cs, y);

                y = section(cs, y - 26, "Symptoms", record.getSymptoms());
                y = section(cs, y - 18, "Diagnosis", record.getDiagnosis());
                section(cs, y - 18, "Prescription", record.getPrescription());

                line(cs, ITALIC, 8, MARGIN, MARGIN,
                        "Generated by CareSync - for questions about this record, contact your care provider.");
            }

            ByteArrayOutputStream out = new ByteArrayOutputStream();
            document.save(out);
            return out.toByteArray();
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to generate prescription PDF", e);
        }
    }

    private float section(PDPageContentStream cs, float y, String label, String value) throws IOException {
        y = line(cs, BOLD, 10.5f, MARGIN, y, label.toUpperCase());
        List<String> lines = wrapText(blankToDash(value), REGULAR, 10.5f, CONTENT_WIDTH);
        for (String textLine : lines) {
            y = line(cs, REGULAR, 10.5f, MARGIN, y - 15, textLine);
        }
        return y;
    }

    private float labelValue(PDPageContentStream cs, float x, float y, String label, String value) throws IOException {
        line(cs, BOLD, 8.5f, x, y, label.toUpperCase());
        return line(cs, REGULAR, 11f, x, y - 15, blankToDash(value));
    }

    private float line(PDPageContentStream cs, PDFont font, float size, float x, float y, String text)
            throws IOException {
        cs.beginText();
        cs.setFont(font, size);
        cs.newLineAtOffset(x, y);
        cs.showText(sanitize(text));
        cs.endText();
        return y;
    }

    private float rule(PDPageContentStream cs, float y) throws IOException {
        cs.setLineWidth(0.75f);
        cs.moveTo(MARGIN, y);
        cs.lineTo(MARGIN + CONTENT_WIDTH, y);
        cs.stroke();
        return y;
    }

    private List<String> wrapText(String text, PDFont font, float fontSize, float maxWidth) throws IOException {
        List<String> lines = new ArrayList<>();
        for (String paragraph : text.split("\n")) {
            StringBuilder current = new StringBuilder();
            for (String word : paragraph.split(" ")) {
                String candidate = current.isEmpty() ? word : current + " " + word;
                float width = font.getStringWidth(sanitize(candidate)) / 1000 * fontSize;
                if (width > maxWidth && !current.isEmpty()) {
                    lines.add(current.toString());
                    current = new StringBuilder(word);
                } else {
                    current = new StringBuilder(candidate);
                }
            }
            lines.add(current.toString());
        }
        return lines;
    }

    private String sanitize(String text) {
        return text == null ? "" : text.replaceAll("[^\\x00-\\xFF]", "?");
    }

    private String nullToDash(String value) {
        return value == null || value.isBlank() ? "-" : value;
    }

    private String blankToDash(String value) {
        return value == null || value.isBlank() ? "-" : value;
    }
}